AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Food Delivery System - Serverless Architecture

Resources:
  # Main Lambda function handling order operations
  # Configured with environment variables, IAM policies, and API Gateway endpoints
  FoodDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: backend/lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          TABLE_NAME: !Ref FoodOrdersTable
          POWERTOOLS_SERVICE_NAME: FoodDelivery
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FoodOrdersTable
        - CloudWatchLogsFullAccess
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FoodDeliveryAlerts.TopicName
        - XRayWriteOnlyPolicy
      Events:
        OrderAPI:
          Type: Api
          Properties:
            Path: /order
            Method: post
            RestApiId: !Ref FoodDeliveryApi
        GetOrderAPI:
          Type: Api
          Properties:
            Path: /order
            Method: get
            RestApiId: !Ref FoodDeliveryApi
        OptionsAPI:
          Type: Api
          Properties:
            Path: /order
            Method: options
            RestApiId: !Ref FoodDeliveryApi
      Timeout: 30
      MemorySize: 128
      Tracing: Active
      Tags:
        Environment: Production
        Project: FoodDelivery
        ManagedBy: SAM
        CostCenter: FoodDelivery

  # DynamoDB table for storing order data
  # Configured with provisioned capacity, encryption, and auto-scaling enabled
  FoodOrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FoodOrders
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        Enabled: true
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: FoodDelivery
        - Key: CostCenter
          Value: FoodDelivery

  # API Gateway REST API
  # Handles HTTP requests and routes them to the Lambda function
  FoodDeliveryApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: FoodDeliveryAPI
      Description: Food Delivery REST API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # SNS Topic for system alerts
  # Used by CloudWatch alarms to notify about errors and throttles
  FoodDeliveryAlerts:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: FoodDeliveryAlerts
      DisplayName: Food Delivery System Alerts

  # CloudWatch Alarm for Lambda Errors
  # Triggers if Lambda function encounters any errors in a 5-minute period
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Lambda-FoodDelivery-Error-Alarm
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FoodDeliveryFunction
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref FoodDeliveryAlerts
      OKActions:
        - !Ref FoodDeliveryAlerts
      AlarmDescription: Alarm if Lambda FoodDeliveryFunction has any errors

  # CloudWatch Alarm for Lambda Throttles
  # Triggers if Lambda function gets throttled more than once in 5 minutes
  # Helps identify when we need to increase concurrency limits
  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Lambda-Throttle-Alarm
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FoodDeliveryFunction
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref FoodDeliveryAlerts
      AlarmDescription: Alarm if Lambda gets throttled

# Output values that can be referenced by other stacks
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${FoodDeliveryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref FoodDeliveryFunction
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref FoodOrdersTable 